name: Flight Scraper

# Add permissions for pushing to the repository
permissions:
  contents: write

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper git operations
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Run flight scraper
      env:
        WIZZ_USERNAME: ${{ secrets.WIZZ_USERNAME }}
        WIZZ_PASSWORD: ${{ secrets.WIZZ_PASSWORD }}
      run: python all_flights.py
    
    - name: Check for changes
      id: git-check
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changes exist
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git commit -m "Update flight data [skip ci]"
        git push 